CREATE TABLE IF NOT EXISTS `mes_wm_return_issue_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `issue_id` bigint DEFAULT NULL,
  `line_id` bigint DEFAULT NULL,
  `material_stock_id` bigint DEFAULT NULL,
  `item_id` bigint DEFAULT NULL,
  `quantity` decimal(14,2) DEFAULT NULL,
  `batch_id` bigint DEFAULT NULL,
  `batch_code` varchar(255) DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `location_id` bigint DEFAULT NULL,
  `area_id` bigint DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_issue_id` (`issue_id`),
  KEY `idx_line_id` (`line_id`),
  KEY `idx_item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `yian_workorder_return_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `workorder_id` bigint NOT NULL,
  `order_no` varchar(32) NOT NULL,
  `issue_id` bigint NOT NULL,
  `issue_code` varchar(64) NOT NULL,
  `item_id` bigint DEFAULT NULL,
  `item_name` varchar(128) NOT NULL,
  `item_spec` varchar(128) DEFAULT NULL,
  `return_quantity` decimal(14,2) NOT NULL,
  `return_reason` varchar(512) NOT NULL,
  `operator_name` varchar(64) NOT NULL,
  `returned_at` datetime NOT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_workorder_id` (`workorder_id`),
  KEY `idx_issue_id` (`issue_id`),
  KEY `idx_item_name_spec` (`item_name`, `item_spec`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
